### ISSUE TITLE
StandAlone Mode

### ISSUE THREAD

**Issue by ajcurtin** [mbabineau/cloudformation-zookeeper#4]
I have tried launching this stack 5x todays following the instructions to a T. I have used this cloudformation script in other environments without a hitch. Right now, my exhibitor shows only 1 zk server and config says "unavailable". /v1/cluster/list shows {"servers":["unavailable"],"port":2181} and the logs show this:

Fri Aug 14 17:04:27 UTC 2015    INFO    State: serving
Fri Aug 14 17:03:58 UTC 2015    INFO    ZooKeeper Server: Starting zookeeper ... STARTED
Fri Aug 14 17:03:57 UTC 2015    ERROR   ZooKeeper Server: Using config: /opt/zookeeper/bin/../conf/zoo.cfg
Fri Aug 14 17:03:57 UTC 2015    INFO    Process started via: /opt/zookeeper/bin/zkServer.sh
Fri Aug 14 17:03:57 UTC 2015    ERROR   ZooKeeper Server: JMX enabled by default
Fri Aug 14 17:03:57 UTC 2015    INFO    jps didn't find instance - assuming ZK is not running
Fri Aug 14 17:03:57 UTC 2015    INFO    Attempting to start/restart ZooKeeper
Fri Aug 14 17:03:57 UTC 2015    INFO    Attempting to stop instance
Fri Aug 14 17:03:57 UTC 2015    INFO    Server list has changed
Fri Aug 14 17:03:57 UTC 2015    INFO    State: down
Fri Aug 14 17:03:26 UTC 2015    INFO    Could not initiate Automatic Instance Management config change. Another process is already making a config change.
Fri Aug 14 17:03:26 UTC 2015    INFO    Automatic Instance Management will change the server list:  ==> 1:unavailable
Fri Aug 14 17:02:55 UTC 2015    ERROR   Monitoring instance (java.lang.NullPointerException,    at com.netflix.exhibitor.core.processes.StandardProcessOperations.prepConfigFile(StandardProcessOperations.java:161),   at com.netflix.exhibitor.core.processes.StandardProcessOperations.startInstance(StandardProcessOperations.java:109),    at com.netflix.exhibitor.core.state.KillRunningInstance.completed(KillRunningInstance.java:41),     at com.netflix.exhibitor.core.activity.ActivityQueue$1.run(ActivityQueue.java:127),     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471),     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334),  at java.util.concurrent.FutureTask.run(FutureTask.java:166),    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146),     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615),     at java.lang.Thread.run(Thread.java:701))
Fri Aug 14 17:02:55 UTC 2015    INFO    Starting in standalone mode
Fri Aug 14 17:02:55 UTC 2015    INFO    jps didn't find instance - assuming ZK is not running
Fri Aug 14 17:02:55 UTC 2015    INFO    Attempting to start/restart ZooKeeper
Fri Aug 14 17:02:55 UTC 2015    INFO    Attempting to stop instance
Fri Aug 14 17:02:55 UTC 2015    INFO    Restarting down/not-serving ZooKeeper after 60222 ms pause
Fri Aug 14 17:02:25 UTC 2015    INFO    ZooKeeper down/not-serving waiting 30126 of 40000 ms before restarting
Fri Aug 14 17:01:55 UTC 2015    ERROR   Monitoring instance (java.lang.NullPointerException,    at com.netflix.exhibitor.core.processes.StandardProcessOperations.prepConfigFile(StandardProcessOperations.java:161),   at com.netflix.exhibitor.core.processes.StandardProcessOperations.startInstance(StandardProcessOperations.java:109),    at com.netflix.exhibitor.core.state.KillRunningInstance.completed(KillRunningInstance.java:41),     at com.netflix.exhibitor.core.activity.ActivityQueue$1.run(ActivityQueue.java:127),     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471),     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334),  at java.util.concurrent.FutureTask.run(FutureTask.java:166),    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146),     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615),     at java.lang.Thread.run(Thread.java:701))
Fri Aug 14 17:01:55 UTC 2015    INFO    Starting in standalone mode
Fri Aug 14 17:01:55 UTC 2015    INFO    jps didn't find instance - assuming ZK is not running
Fri Aug 14 17:01:55 UTC 2015    INFO    Attempting to start/restart ZooKeeper
Fri Aug 14 17:01:55 UTC 2015    INFO    Attempting to stop instance
Fri Aug 14 17:01:55 UTC 2015    INFO    State: down
Fri Aug 14 17:01:23 UTC 2015    INFO    Exhibitor started

**Comment by armaseg** [comment]
Same problem here

**Comment by armaseg** [comment]
I had the same problem when my EC2 instance didn't have a public IP, #10 should fix it
